-- MySQL Script generated by MySQL Workbench
-- Fri Dec  8 18:19:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Osoblje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Osoblje` (
  `id` INT NOT NULL,
  `jmbg` INT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `plata` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Izvođač`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Izvođač` (
  `Osoblje_id` INT NOT NULL,
  `instrument` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Osoblje_id`),
  CONSTRAINT `fk_table1_Osoblje`
    FOREIGN KEY (`Osoblje_id`)
    REFERENCES `Osoblje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dirigent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dirigent` (
  `Osoblje_id` INT NOT NULL,
  `godineIskustva` INT NOT NULL,
  `konzervatorijum` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Osoblje_id`),
  CONSTRAINT `fk_table2_Osoblje1`
    FOREIGN KEY (`Osoblje_id`)
    REFERENCES `Osoblje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Higijeničar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Higijeničar` (
  `Osoblje_id` INT NOT NULL,
  `stručnaSprema` VARCHAR(45) NOT NULL,
  `sindikat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Osoblje_id`),
  CONSTRAINT `fk_table3_Osoblje1`
    FOREIGN KEY (`Osoblje_id`)
    REFERENCES `Osoblje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blagajna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blagajna` (
  `id` INT NOT NULL,
  `radnoVreme` TIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blagajnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blagajnik` (
  `Osoblje_id` INT NOT NULL,
  `Blagajna_id` INT NOT NULL,
  `preferiranaSmena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Osoblje_id`),
  INDEX `fk_Blagajnik_Blagajna1_idx` (`Blagajna_id` ASC),
  CONSTRAINT `fk_table4_Osoblje1`
    FOREIGN KEY (`Osoblje_id`)
    REFERENCES `Osoblje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Blagajnik_Blagajna1`
    FOREIGN KEY (`Blagajna_id`)
    REFERENCES `Blagajna` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoncertnaSala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoncertnaSala` (
  `id` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `brojMesta` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zadužen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zadužen` (
  `Higijeničar_Osoblje_id` INT NOT NULL,
  `KoncertnaSala_id` INT NOT NULL,
  PRIMARY KEY (`Higijeničar_Osoblje_id`, `KoncertnaSala_id`),
  INDEX `fk_Higijeničar_has_KoncertnaSala_KoncertnaSala1_idx` (`KoncertnaSala_id` ASC),
  INDEX `fk_Higijeničar_has_KoncertnaSala_Higijeničar1_idx` (`Higijeničar_Osoblje_id` ASC),
  CONSTRAINT `fk_Higijeničar_has_KoncertnaSala_Higijeničar1`
    FOREIGN KEY (`Higijeničar_Osoblje_id`)
    REFERENCES `Higijeničar` (`Osoblje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Higijeničar_has_KoncertnaSala_KoncertnaSala1`
    FOREIGN KEY (`KoncertnaSala_id`)
    REFERENCES `KoncertnaSala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kompozicija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kompozicija` (
  `id` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `kompozitor` VARCHAR(45) NOT NULL,
  `zemljaPorekla` VARCHAR(45) NOT NULL,
  `godinaPorekla` INT NOT NULL,
  `trajanje` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Čin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Čin` (
  `id` INT NOT NULL,
  `Kompozicija_id` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `Kompozicija_id`),
  INDEX `fk_Čin_Kompozicija1_idx` (`Kompozicija_id` ASC),
  CONSTRAINT `fk_Čin_Kompozicija1`
    FOREIGN KEY (`Kompozicija_id`)
    REFERENCES `Kompozicija` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Orkestar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Orkestar` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pripada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pripada` (
  `Izvođač_Osoblje_id` INT NOT NULL,
  `Orkestar_id` INT NOT NULL,
  PRIMARY KEY (`Izvođač_Osoblje_id`, `Orkestar_id`),
  INDEX `fk_Izvođač_has_Orkestar_Orkestar1_idx` (`Orkestar_id` ASC),
  INDEX `fk_Izvođač_has_Orkestar_Izvođač1_idx` (`Izvođač_Osoblje_id` ASC),
  CONSTRAINT `fk_Izvođač_has_Orkestar_Izvođač1`
    FOREIGN KEY (`Izvođač_Osoblje_id`)
    REFERENCES `Izvođač` (`Osoblje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Izvođač_has_Orkestar_Orkestar1`
    FOREIGN KEY (`Orkestar_id`)
    REFERENCES `Orkestar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diriguje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diriguje` (
  `Dirigent_Osoblje_id` INT NOT NULL,
  `Orkestar_id` INT NOT NULL,
  PRIMARY KEY (`Dirigent_Osoblje_id`, `Orkestar_id`),
  INDEX `fk_Dirigent_has_Orkestar_Orkestar1_idx` (`Orkestar_id` ASC),
  INDEX `fk_Dirigent_has_Orkestar_Dirigent1_idx` (`Dirigent_Osoblje_id` ASC),
  CONSTRAINT `fk_Dirigent_has_Orkestar_Dirigent1`
    FOREIGN KEY (`Dirigent_Osoblje_id`)
    REFERENCES `Dirigent` (`Osoblje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dirigent_has_Orkestar_Orkestar1`
    FOREIGN KEY (`Orkestar_id`)
    REFERENCES `Orkestar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Izvodi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Izvodi` (
  `Kompozicija_id` INT NOT NULL,
  `Diriguje_Dirigent_Osoblje_id` INT NOT NULL,
  `Diriguje_Orkestar_id` INT NOT NULL,
  PRIMARY KEY (`Kompozicija_id`, `Diriguje_Dirigent_Osoblje_id`, `Diriguje_Orkestar_id`),
  INDEX `fk_Kompozicija_has_Diriguje_Diriguje1_idx` (`Diriguje_Dirigent_Osoblje_id` ASC, `Diriguje_Orkestar_id` ASC),
  INDEX `fk_Kompozicija_has_Diriguje_Kompozicija1_idx` (`Kompozicija_id` ASC),
  CONSTRAINT `fk_Kompozicija_has_Diriguje_Kompozicija1`
    FOREIGN KEY (`Kompozicija_id`)
    REFERENCES `Kompozicija` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kompozicija_has_Diriguje_Diriguje1`
    FOREIGN KEY (`Diriguje_Dirigent_Osoblje_id` , `Diriguje_Orkestar_id`)
    REFERENCES `Diriguje` (`Dirigent_Osoblje_id` , `Orkestar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Nastupa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nastupa` (
  `Izvodi_Kompozicija_id` INT NOT NULL,
  `Izvodi_Diriguje_Dirigent_Osoblje_id` INT NOT NULL,
  `Izvodi_Diriguje_Orkestar_id` INT NOT NULL,
  `KoncertnaSala_id` INT NOT NULL,
  `vreme` TIME NOT NULL,
  PRIMARY KEY (`KoncertnaSala_id`, `vreme`),
  INDEX `fk_Izvodi_has_KoncertnaSala_KoncertnaSala1_idx` (`KoncertnaSala_id` ASC),
  INDEX `fk_Izvodi_has_KoncertnaSala_Izvodi1_idx` (`Izvodi_Kompozicija_id` ASC, `Izvodi_Diriguje_Dirigent_Osoblje_id` ASC, `Izvodi_Diriguje_Orkestar_id` ASC),
  CONSTRAINT `fk_Izvodi_has_KoncertnaSala_Izvodi1`
    FOREIGN KEY (`Izvodi_Kompozicija_id` , `Izvodi_Diriguje_Dirigent_Osoblje_id` , `Izvodi_Diriguje_Orkestar_id`)
    REFERENCES `Izvodi` (`Kompozicija_id` , `Diriguje_Dirigent_Osoblje_id` , `Diriguje_Orkestar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Izvodi_has_KoncertnaSala_KoncertnaSala1`
    FOREIGN KEY (`KoncertnaSala_id`)
    REFERENCES `KoncertnaSala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
