-- MySQL Script generated by MySQL Workbench
-- Wed Dec  6 18:00:56 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Osoblje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Osoblje` (
  `id` INT NOT NULL,
  `jmbg` INT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `plata` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Izvođač`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Izvođač` (
  `Osoblje_id` INT NOT NULL,
  `instrument` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Osoblje_id`),
  CONSTRAINT `fk_table1_Osoblje`
    FOREIGN KEY (`Osoblje_id`)
    REFERENCES `mydb`.`Osoblje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dirigent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dirigent` (
  `Osoblje_id` INT NOT NULL,
  `godineIskustva` INT NOT NULL,
  `konzervatorijum` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Osoblje_id`),
  CONSTRAINT `fk_table2_Osoblje1`
    FOREIGN KEY (`Osoblje_id`)
    REFERENCES `mydb`.`Osoblje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Higijeničar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Higijeničar` (
  `Osoblje_id` INT NOT NULL,
  `stručnaSprema` VARCHAR(45) NOT NULL,
  `sindikat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Osoblje_id`),
  CONSTRAINT `fk_table3_Osoblje1`
    FOREIGN KEY (`Osoblje_id`)
    REFERENCES `mydb`.`Osoblje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Blagajna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Blagajna` (
  `id` INT NOT NULL,
  `radnoVreme` TIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Blagajnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Blagajnik` (
  `Osoblje_id` INT NOT NULL,
  `Blagajna_id` INT NOT NULL,
  `preferiranaSmena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Osoblje_id`),
  INDEX `fk_Blagajnik_Blagajna1_idx` (`Blagajna_id` ASC),
  CONSTRAINT `fk_table4_Osoblje1`
    FOREIGN KEY (`Osoblje_id`)
    REFERENCES `mydb`.`Osoblje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Blagajnik_Blagajna1`
    FOREIGN KEY (`Blagajna_id`)
    REFERENCES `mydb`.`Blagajna` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KoncertnaSala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KoncertnaSala` (
  `id` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `brojMesta` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zadužen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zadužen` (
  `Higijeničar_Osoblje_id` INT NOT NULL,
  `KoncertnaSala_id` INT NOT NULL,
  PRIMARY KEY (`Higijeničar_Osoblje_id`, `KoncertnaSala_id`),
  INDEX `fk_Higijeničar_has_KoncertnaSala_KoncertnaSala1_idx` (`KoncertnaSala_id` ASC),
  INDEX `fk_Higijeničar_has_KoncertnaSala_Higijeničar1_idx` (`Higijeničar_Osoblje_id` ASC),
  CONSTRAINT `fk_Higijeničar_has_KoncertnaSala_Higijeničar1`
    FOREIGN KEY (`Higijeničar_Osoblje_id`)
    REFERENCES `mydb`.`Higijeničar` (`Osoblje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Higijeničar_has_KoncertnaSala_KoncertnaSala1`
    FOREIGN KEY (`KoncertnaSala_id`)
    REFERENCES `mydb`.`KoncertnaSala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kompozicija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kompozicija` (
  `id` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `kompozitor` VARCHAR(45) NOT NULL,
  `zemljaPorekla` VARCHAR(45) NOT NULL,
  `godinaPorekla` INT NOT NULL,
  `trajanje` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Čin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Čin` (
  `id` INT NOT NULL,
  `Kompozicija_id` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `Kompozicija_id`),
  INDEX `fk_Čin_Kompozicija1_idx` (`Kompozicija_id` ASC),
  CONSTRAINT `fk_Čin_Kompozicija1`
    FOREIGN KEY (`Kompozicija_id`)
    REFERENCES `mydb`.`Kompozicija` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Izvođenje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Izvođenje` (
  `Izvođač_Osoblje_id` INT NOT NULL,
  `Kompozicija_id` INT NOT NULL,
  `Dirigent_Osoblje_id` INT NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Izvođač_has_Kompozicija_Kompozicija1_idx` (`Kompozicija_id` ASC),
  INDEX `fk_Izvođač_has_Kompozicija_Izvođač1_idx` (`Izvođač_Osoblje_id` ASC),
  INDEX `fk_Izvođač_has_Kompozicija_Dirigent1_idx` (`Dirigent_Osoblje_id` ASC),
  CONSTRAINT `fk_Izvođač_has_Kompozicija_Izvođač1`
    FOREIGN KEY (`Izvođač_Osoblje_id`)
    REFERENCES `mydb`.`Izvođač` (`Osoblje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Izvođač_has_Kompozicija_Kompozicija1`
    FOREIGN KEY (`Kompozicija_id`)
    REFERENCES `mydb`.`Kompozicija` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Izvođač_has_Kompozicija_Dirigent1`
    FOREIGN KEY (`Dirigent_Osoblje_id`)
    REFERENCES `mydb`.`Dirigent` (`Osoblje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Održava`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Održava` (
  `KoncertnaSala_id` INT NOT NULL,
  `vreme` TIME NOT NULL,
  `Izvođenje_id` INT NOT NULL,
  PRIMARY KEY (`KoncertnaSala_id`, `vreme`),
  INDEX `fk_Održava_Izvođenje1_idx` (`Izvođenje_id` ASC),
  CONSTRAINT `fk_Održava_KoncertnaSala1`
    FOREIGN KEY (`KoncertnaSala_id`)
    REFERENCES `mydb`.`KoncertnaSala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Održava_Izvođenje1`
    FOREIGN KEY (`Izvođenje_id`)
    REFERENCES `mydb`.`Izvođenje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
