-- MySQL Script generated by MySQL Workbench
-- Fri Dec  8 18:19:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema filharmonija
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `filharmonija` ;

-- -----------------------------------------------------
-- Schema filharmonija
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `filharmonija` DEFAULT CHARACTER SET utf8 ;
USE `filharmonija` ;

-- -----------------------------------------------------
-- Table `Osoblje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Osoblje` (
  `id` INT NOT NULL,
  `jmbg` BIGINT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `plata` INT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Izvodjac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Izvodjac` (
  `Osoblje_id` INT NOT NULL,
  `instrument` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Osoblje_id`),
  CONSTRAINT `fk_table1_Osoblje`
    FOREIGN KEY (`Osoblje_id`)
    REFERENCES `Osoblje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dirigent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dirigent` (
  `Osoblje_id` INT NOT NULL,
  `godineIskustva` INT NOT NULL,
  `konzervatorijum` VARCHAR(45) NOT NULL,
  `penzija` BOOLEAN NOT NULL,
  PRIMARY KEY (`Osoblje_id`),
  CONSTRAINT `fk_table2_Osoblje1`
    FOREIGN KEY (`Osoblje_id`)
    REFERENCES `Osoblje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Higijenicar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Higijenicar` (
  `Osoblje_id` INT NOT NULL,
  `strucnaSprema` VARCHAR(45) NOT NULL,
  `sindikat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Osoblje_id`),
  CONSTRAINT `fk_table3_Osoblje1`
    FOREIGN KEY (`Osoblje_id`)
    REFERENCES `Osoblje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blagajna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blagajna` (
  `id` INT NOT NULL,
  `radnoVreme` TIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blagajnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blagajnik` (
  `Osoblje_id` INT NOT NULL,
  `Blagajna_id` INT NOT NULL,
  `preferiranaSmena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Osoblje_id`),
  INDEX `fk_Blagajnik_Blagajna1_idx` (`Blagajna_id` ASC),
  CONSTRAINT `fk_table4_Osoblje1`
    FOREIGN KEY (`Osoblje_id`)
    REFERENCES `Osoblje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Blagajnik_Blagajna1`
    FOREIGN KEY (`Blagajna_id`)
    REFERENCES `Blagajna` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoncertnaSala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoncertnaSala` (
  `id` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `brojMesta` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zaduzen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zaduzen` (
  `Higijenicar_Osoblje_id` INT NOT NULL,
  `KoncertnaSala_id` INT NOT NULL,
  PRIMARY KEY (`Higijenicar_Osoblje_id`, `KoncertnaSala_id`),
  INDEX `fk_Higijenicar_has_KoncertnaSala_KoncertnaSala1_idx` (`KoncertnaSala_id` ASC),
  INDEX `fk_Higijenicar_has_KoncertnaSala_Higijenicar1_idx` (`Higijenicar_Osoblje_id` ASC),
  CONSTRAINT `fk_Higijenicar_has_KoncertnaSala_Higijenicar1`
    FOREIGN KEY (`Higijenicar_Osoblje_id`)
    REFERENCES `Higijenicar` (`Osoblje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Higijenicar_has_KoncertnaSala_KoncertnaSala1`
    FOREIGN KEY (`KoncertnaSala_id`)
    REFERENCES `KoncertnaSala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kompozicija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kompozicija` (
  `id` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `kompozitor` VARCHAR(45) NOT NULL,
  `zemljaPorekla` VARCHAR(45) NOT NULL,
  `godinaPorekla` INT NOT NULL,
  `trajanje` INT NOT NULL,
  `brojCinova` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cin` (
  `id` INT NOT NULL,
  `Kompozicija_id` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `Kompozicija_id`),
  INDEX `fk_Cin_Kompozicija1_idx` (`Kompozicija_id` ASC),
  CONSTRAINT `fk_Cin_Kompozicija1`
    FOREIGN KEY (`Kompozicija_id`)
    REFERENCES `Kompozicija` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Orkestar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Orkestar` (
  `id` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pripada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pripada` (
  `Izvodjac_Osoblje_id` INT NOT NULL,
  `Orkestar_id` INT NOT NULL,
  PRIMARY KEY (`Izvodjac_Osoblje_id`, `Orkestar_id`),
  INDEX `fk_Izvodjac_has_Orkestar_Orkestar1_idx` (`Orkestar_id` ASC),
  INDEX `fk_Izvodjac_has_Orkestar_Izvodjac1_idx` (`Izvodjac_Osoblje_id` ASC),
  CONSTRAINT `fk_Izvodjac_has_Orkestar_Izvodjac1`
    FOREIGN KEY (`Izvodjac_Osoblje_id`)
    REFERENCES `Izvodjac` (`Osoblje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Izvodjac_has_Orkestar_Orkestar1`
    FOREIGN KEY (`Orkestar_id`)
    REFERENCES `Orkestar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diriguje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diriguje` (
  `Dirigent_Osoblje_id` INT NOT NULL,
  `Orkestar_id` INT NOT NULL,
  PRIMARY KEY (`Dirigent_Osoblje_id`, `Orkestar_id`),
  INDEX `fk_Dirigent_has_Orkestar_Orkestar1_idx` (`Orkestar_id` ASC),
  INDEX `fk_Dirigent_has_Orkestar_Dirigent1_idx` (`Dirigent_Osoblje_id` ASC),
  CONSTRAINT `fk_Dirigent_has_Orkestar_Dirigent1`
    FOREIGN KEY (`Dirigent_Osoblje_id`)
    REFERENCES `Dirigent` (`Osoblje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dirigent_has_Orkestar_Orkestar1`
    FOREIGN KEY (`Orkestar_id`)
    REFERENCES `Orkestar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Izvodi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Izvodi` (
  `Kompozicija_id` INT NOT NULL,
  `Diriguje_Dirigent_Osoblje_id` INT NOT NULL,
  `Diriguje_Orkestar_id` INT NOT NULL,
  PRIMARY KEY (`Kompozicija_id`, `Diriguje_Dirigent_Osoblje_id`, `Diriguje_Orkestar_id`),
  INDEX `fk_Kompozicija_has_Diriguje_Diriguje1_idx` (`Diriguje_Dirigent_Osoblje_id` ASC, `Diriguje_Orkestar_id` ASC),
  INDEX `fk_Kompozicija_has_Diriguje_Kompozicija1_idx` (`Kompozicija_id` ASC),
  CONSTRAINT `fk_Kompozicija_has_Diriguje_Kompozicija1`
    FOREIGN KEY (`Kompozicija_id`)
    REFERENCES `Kompozicija` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kompozicija_has_Diriguje_Diriguje1`
    FOREIGN KEY (`Diriguje_Dirigent_Osoblje_id` , `Diriguje_Orkestar_id`)
    REFERENCES `Diriguje` (`Dirigent_Osoblje_id` , `Orkestar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Nastupa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nastupa` (
  `Izvodi_Kompozicija_id` INT NOT NULL,
  `Izvodi_Diriguje_Dirigent_Osoblje_id` INT NOT NULL,
  `Izvodi_Diriguje_Orkestar_id` INT NOT NULL,
  `KoncertnaSala_id` INT NOT NULL,
  `vreme` TIME NOT NULL,
  PRIMARY KEY (`KoncertnaSala_id`, `vreme`),
  INDEX `fk_Izvodi_has_KoncertnaSala_KoncertnaSala1_idx` (`KoncertnaSala_id` ASC),
  INDEX `fk_Izvodi_has_KoncertnaSala_Izvodi1_idx` (`Izvodi_Kompozicija_id` ASC, `Izvodi_Diriguje_Dirigent_Osoblje_id` ASC, `Izvodi_Diriguje_Orkestar_id` ASC),
  CONSTRAINT `fk_Izvodi_has_KoncertnaSala_Izvodi1`
    FOREIGN KEY (`Izvodi_Kompozicija_id` , `Izvodi_Diriguje_Dirigent_Osoblje_id` , `Izvodi_Diriguje_Orkestar_id`)
    REFERENCES `Izvodi` (`Kompozicija_id` , `Diriguje_Dirigent_Osoblje_id` , `Diriguje_Orkestar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Izvodi_has_KoncertnaSala_KoncertnaSala1`
    FOREIGN KEY (`KoncertnaSala_id`)
    REFERENCES `KoncertnaSala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


delimiter $$

CREATE TRIGGER afterUpdateOnHigijenicar
AFTER UPDATE ON Higijenicar
FOR EACH ROW
BEGIN
  UPDATE Osoblje
  SET plata = plata + 5000
  WHERE id = new.Osoblje_id;
END;
$$

CREATE TRIGGER beforeInsertOnIzvodjac
BEFORE INSERT ON Izvodjac
FOR EACH ROW
BEGIN
  UPDATE Osoblje
  SET plata = 70000
  WHERE id = new.Osoblje_id;
END;
$$

CREATE TRIGGER beforeInsertOnHigijenicar
BEFORE INSERT ON Higijenicar
FOR EACH ROW
BEGIN
  UPDATE Osoblje
  SET plata = 20000
  WHERE id = new.Osoblje_id;
END;
$$

CREATE TRIGGER beforeInsertOnDirigent
BEFORE INSERT ON Dirigent
FOR EACH ROW
BEGIN
  UPDATE Osoblje
  SET plata = 100000
  WHERE id = new.Osoblje_id;
END;
$$

CREATE TRIGGER beforeInsertOnBlagajnik
BEFORE INSERT ON Blagajnik
FOR EACH ROW
BEGIN
  UPDATE Osoblje
  SET plata = 40000
  WHERE id = new.Osoblje_id;
END;
$$